config/routes.rb
Adminsite::Engine.routes.draw do
  devise_for :adminsite_admin_user, class_name: 'Adminsite::AdminUser',
             :controllers => { :sessions => "adminsite/admin_user_sessions" }

  namespace Adminsite.config.admin_namespace, as: :admin, module: :admin do
    Adminsite.register_routes(self)

    root      :to => 'adminsite_pages#index'
  end

  get '/:page_url(.:format)(/:id)' => 'contents#show',
      :constraints => lambda { |req|
                                Adminsite::ContentsController.find_page_by_url(req.params[:page_url], req.params[:format]).present? &&
                                 ( req.params[:id].nil? || req.params[:id].try(:match, /\A[0-9a-zA-Z]*\z/).present? )
                              }

end

app/controllers/adminsite/admin/adminsite_pages_controller.rb
class Adminsite::Admin::AdminsitePagesController < Adminsite::Admin::ResourcesController

  def new
    @file_assets = Adminsite::FileAsset.all
    super
  end

  def edit
    @file_assets = Adminsite::FileAsset.all
    super
  end

  def update
    @file_assets = Adminsite::FileAsset.all
    super
    @resource.cleanup_cached
  end

  def destroy
    @resource.cleanup_cached
    super
  end

  protected

  def order_params
    'title ASC'
  end

  def resource_admin_config
    # Adminsite::Admin::ResourcesController.resource_admin_config
    super
  end

  def self.resource_class
    Adminsite::Page
  end

end

app/views/adminsite/admin/adminsite_pages/edit.html.haml
= render :file => 'adminsite/admin/resources/edit'

= render :partial => 'adminsite/admin/shared/syntax_help'
= render :partial => 'adminsite/admin/shared/page_assets_list'
.clear

app/views/adminsite/admin/adminsite_pages/index.html.haml
- if Adminsite::Page.any?
  = render :file => 'adminsite/admin/resources/index'
- elsif Adminsite::PageLayout.exists?
  - content_for :header_left do
    = "Listing #{label_resource_class_plural}"
  - content_for :header_right do
    #action_bar
      = link_to_new "New #{label_resource_class}"
  There are no pages. Go ahead and
  #{link_to 'add the first one', new_admin_adminsite_page_path}.
- else
  - content_for :header_left do
    = "Listing #{label_resource_class_plural}"
  - content_for :header_right do
    #action_bar
      = link_to_new "New #{label_resource_class}"
  You should #{link_to 'add a page layout', new_admin_adminsite_page_layout_path}
  before adding your first page.

app/views/adminsite/admin/adminsite_pages/new.html.haml
= render :file => 'adminsite/admin/resources/new'

= render :partial => 'adminsite/admin/shared/syntax_help'
= render :partial => 'adminsite/admin/shared/page_assets_list'