config/routes.rb
Adminsite::Engine.routes.draw do
  devise_for :adminsite_admin_user, class_name: 'Adminsite::AdminUser',
             :controllers => { :sessions => "adminsite/admin_user_sessions" }

  namespace Adminsite.config.admin_namespace, as: :admin, module: :admin do
    Adminsite.register_routes(self)

    root      :to => 'adminsite_pages#index'
  end

  get '/:page_url(.:format)(/:id)' => 'contents#show',
      :constraints => lambda { |req|
                                Adminsite::ContentsController.find_page_by_url(req.params[:page_url], req.params[:format]).present? &&
                                 ( req.params[:id].nil? || req.params[:id].try(:match, /\A[0-9a-zA-Z]*\z/).present? )
                              }

end

app/views/adminsite/admin/shared/_admin_menu.html.haml
#admin_menu.menu
  %ul
    = menu_item 'Dashboard', admin_dashboard_index_path , ['dashboard']
    = yield :admin_menu
  %ul
    = menu_item 'Log out', destroy_adminsite_admin_user_session_path, ['admin_user_sessions'], 'log_out', :delete
.clearfix

app/views/adminsite/admin/shared/_content_menu.html.haml
#content_menu.menu
  %ul
    = yield :content_menu
.clearfix

app/views/adminsite/admin/shared/_page_assets_list.html.haml
- if @file_assets.present? && @file_assets.any?
  #page-assets-list
    %h2 Assets
    %ul
      - @file_assets.each do |asset|
        %li= asset.attachment_file_name

app/views/adminsite/admin/shared/_syntax_help.html.haml
#syntax-help
  %h2 Liquid parameters
  %p
    %a{ :href => "http://www.liquidmarkup.org/", :target => "_blank" }<
      Liquid template language
    is available, so if you have a user
    %em object
    available you can do something like this:
    %pre {{ user.first_name }}
    Or if you have a collection of objects like
    %i products
    you can:
    ~ "<pre>{% for product in products %}\n  {{ product.title }}\n{% endfor %}</pre>"

  %h2 Including assets
  %p
    You can include assets using this syntax:
    %pre &lt;img src="{% asset logo.jpg %}" /&gt;
    This requires you have uploaded a logo.jpg
    %br
    %strong
      NOTE:
    if you are uploading on Cloudfile CDN, the syntax above will
    replace the path with Cloudfile url.